import type { Category } from "./types";

export const mongodb: Category = {
  slug: "mongodb",
  title: "MongoDB",
  description:
    "MongoDB from CRUD and the aggregation pipeline to indexing, schema design, replica sets, sharding, transactions, and the WiredTiger storage engine.",
  icon: "🍃",
  questions: [
    // ───────── EASY ─────────
    {
      id: "what-is-mongodb",
      title: "What is MongoDB?",
      difficulty: "easy",
      question: "What is MongoDB and what kind of database is it?",
      answer: `**MongoDB** is a **document database** — it stores records as flexible **BSON** (binary JSON) documents inside **collections**. There's no table schema at the storage level; documents in the same collection can differ in shape.

**Key characteristics:**
- **Flexible schema** — evolve data shapes without migrations at the DB level.
- **Rich query language** — filters, projections, aggregations, updates with operators, geospatial, text search.
- **Horizontal scaling** via **sharding**; high availability via **replica sets**.
- **ACID transactions** (multi-document, since 4.0 on replica sets, 4.2 on sharded clusters).
- **WiredTiger** storage engine (compression, document-level locking).
- **Developer ergonomics** — drivers for every major language with idiomatic APIs; query language maps naturally to JS objects.

**When it shines:** document-shaped data where an aggregate is the natural unit (user + profile + settings), read/write patterns built around those aggregates, and flexible/evolving schemas.

**When to hesitate:** heavily relational data with many joins, strict multi-entity transactions everywhere, or when your team already operates a good relational DB happily.`,
      tags: ["fundamentals"],
    },
    {
      id: "document-collection",
      title: "Documents, collections, databases",
      difficulty: "easy",
      question: "How is MongoDB data organized?",
      answer: `The hierarchy is:

\`\`\`
Cluster → Database → Collection → Document → Field
\`\`\`

- **Database** — namespace; a single MongoDB instance can hold many.
- **Collection** — a group of documents (equivalent of a table).
- **Document** — a single record as JSON-like data (up to 16 MB).
- **Field** — a key/value pair inside a document.

\`\`\`js
// collection: users
{
  "_id": ObjectId("..."),
  "email": "ada@example.com",
  "profile": { "name": "Ada", "country": "TR" },
  "roles": ["admin", "editor"],
  "createdAt": ISODate("2026-01-01T10:00:00Z")
}
\`\`\`

**Notes:**
- **Documents in one collection need not share fields.** A validator can enforce shape if you want (\`\$jsonSchema\`).
- **\`_id\`** is the primary key (covered separately). Added automatically if you don't supply one.
- Collections are created lazily on first insert.
- MongoDB supports **views** (read-only queries) and **time-series collections** (optimized for metrics).`,
      tags: ["fundamentals"],
    },
    {
      id: "objectid",
      title: "ObjectId and the _id field",
      difficulty: "easy",
      question: "What is ObjectId and why is it the default _id?",
      answer: `**\`ObjectId\`** is MongoDB's default 12-byte identifier:

\`\`\`
 4 bytes  | 5 bytes               | 3 bytes
timestamp | random (per process)  | counter
\`\`\`

- **Roughly sortable by insertion time** (the leading 4 bytes are a Unix timestamp).
- **Globally unique** across machines and processes (collision-proof in practice).
- **Generated by the driver** before insert — no round-trip needed.

\`\`\`js
const id = new ObjectId();                      // new one
id.getTimestamp();                              // Date it was created
ObjectId.isValid("65dc123456789abcdef01234");   // validation
\`\`\`

**You can use anything as \`_id\`** — a string, a composite object, a UUID, your own scheme. Rules:
- Must be unique within the collection.
- Cannot be changed (\`_id\` is immutable after insert).
- Indexed automatically and queried extremely often — keep it small and stable.

**Why not UUID by default?** ObjectIds are smaller (12 bytes vs 16), time-ordered (better index locality), and easy to generate on the client. But UUIDs are fine if you need opaque, non-time-revealing IDs.`,
      tags: ["fundamentals"],
    },
    {
      id: "crud-basics",
      title: "Basic CRUD operations",
      difficulty: "easy",
      question: "What are the basic CRUD operations in MongoDB?",
      answer: `\`\`\`js
// Create
db.users.insertOne({ email: "ada@example.com", age: 30 });
db.users.insertMany([{...}, {...}]);

// Read
db.users.findOne({ _id: id });
db.users.find({ age: { \$gte: 18 } }).limit(50);
db.users.countDocuments({ active: true });

// Update
db.users.updateOne({ _id: id }, { \$set: { lastSeenAt: new Date() } });
db.users.updateMany({ active: false }, { \$set: { archived: true } });
db.users.replaceOne({ _id: id }, newDocument);

// Delete
db.users.deleteOne({ _id: id });
db.users.deleteMany({ archived: true });

// Upsert — insert if not found, update if found
db.users.updateOne({ email }, { \$set: { lastSeenAt: new Date() } }, { upsert: true });

// Find + modify atomically
db.queue.findOneAndUpdate(
  { status: "ready" },
  { \$set: { status: "processing" } },
  { sort: { priority: -1 }, returnDocument: "after" }
);
\`\`\`

**Important:**
- All updates need update operators (\`\$set\`, \`\$inc\`, \`\$push\` ...) or they replace the whole document.
- Queries without an index may perform a **full collection scan** — fine in dev, catastrophic in prod.
- \`findOneAndUpdate\` is the atomic "claim an item from a queue" primitive.`,
      tags: ["fundamentals", "crud"],
    },
    {
      id: "query-operators",
      title: "Query operators",
      difficulty: "easy",
      question: "What are the common query operators?",
      answer: `Operators use a **\`\$\`** prefix.

**Comparison:**
- \`\$eq\`, \`\$ne\`, \`\$gt\`, \`\$gte\`, \`\$lt\`, \`\$lte\`
- \`\$in\`, \`\$nin\` — value in / not in array
\`\`\`js
db.users.find({ age: { \$gte: 18, \$lt: 65 } });
db.users.find({ role: { \$in: ["admin", "editor"] } });
\`\`\`

**Logical:**
- \`\$and\`, \`\$or\`, \`\$nor\`, \`\$not\`
\`\`\`js
db.users.find({ \$or: [{ age: { \$lt: 13 } }, { age: { \$gt: 100 } }] });
\`\`\`

**Element:**
- \`\$exists\` — field exists (use sparingly, not sargable)
- \`\$type\` — BSON type check

**Array:**
- \`\$all\` — contains all given values
- \`\$size\` — exact length
- \`\$elemMatch\` — at least one element matches multiple criteria
\`\`\`js
db.orders.find({ items: { \$elemMatch: { sku: "A1", qty: { \$gte: 2 } } } });
\`\`\`

**Evaluation:**
- \`\$regex\` — pattern match (anchored regexes can use indexes)
- \`\$expr\` — allow aggregation expressions in a query (compare two fields)
- \`\$text\` — full-text search (requires a text index)
\`\`\`js
db.posts.find({ \$expr: { \$gt: ["\$createdAt", "\$updatedAt"] } });
\`\`\`

**Geospatial:** \`\$geoWithin\`, \`\$near\`, \`\$geoIntersects\`.`,
      tags: ["core", "queries"],
    },
    {
      id: "projections",
      title: "Projections and sorting",
      difficulty: "easy",
      question: "How do you limit fields returned and sort results?",
      answer: `**Projection** selects the fields you want. Implicit: \`_id\` is always returned unless explicitly excluded.

\`\`\`js
// Include only email and createdAt
db.users.find({}, { email: 1, createdAt: 1 });

// Exclude password hash
db.users.find({}, { passwordHash: 0 });

// You cannot mix inclusion and exclusion in the same query
// (except for excluding _id while including other fields)
db.users.find({}, { _id: 0, email: 1 });
\`\`\`

**Nested / array projections:**
\`\`\`js
db.users.find({}, { "profile.name": 1 });
db.orders.find({}, { "items.\$": 1 });           // positional — matches query
db.orders.find({}, { items: { \$slice: 3 } });   // first 3
db.orders.find({}, { items: { \$elemMatch: { sku: "A1" } } });
\`\`\`

**Sort:**
\`\`\`js
db.users.find().sort({ createdAt: -1 }).limit(20);
\`\`\`

\`1\` ascending, \`-1\` descending. Sorting without a matching index performs an in-memory sort limited to 100 MB — beyond that Mongo errors. Ensure the sort fields are indexed for large result sets.

**Pagination:** avoid \`skip + limit\` for large offsets (linear scan). Prefer **range-based ("keyset") pagination**: \`find({ _id: { \$gt: lastId } }).limit(20)\`.`,
      tags: ["core", "queries"],
    },
    {
      id: "update-operators",
      title: "Update operators",
      difficulty: "easy",
      question: "What are the important update operators?",
      answer: `**Field operators:**
- \`\$set\` / \`\$unset\` — assign / remove a field
- \`\$inc\` — increment numeric
- \`\$mul\` — multiply
- \`\$min\` / \`\$max\` — only if new value is smaller / larger
- \`\$rename\` — rename a field
- \`\$currentDate\` — set to server time

\`\`\`js
db.users.updateOne({ _id: id }, {
  \$set: { email: "new@x.com" },
  \$inc: { loginCount: 1 },
  \$currentDate: { lastLoginAt: true }
});
\`\`\`

**Array operators:**
- \`\$push\` — append (with \`\$each\`, \`\$slice\`, \`\$sort\`, \`\$position\`)
- \`\$pull\` — remove matching elements
- \`\$addToSet\` — push only if not present
- \`\$pop\` — remove first/last
- \`\$[<identifier>]\` / \`\$[]\` — positional operators for nested updates

\`\`\`js
db.posts.updateOne({ _id: postId }, {
  \$push: { comments: { \$each: [c1, c2], \$slice: -100 } }, // keep last 100
  \$addToSet: { tags: "featured" }
});

// Update specific matching elements
db.posts.updateOne(
  { _id: postId, "comments.author": "spammer" },
  { \$set: { "comments.\$.hidden": true } }
);

// Update all matching
db.posts.updateMany({}, { \$set: { "comments.\$[c].reviewed": true } },
  { arrayFilters: [{ "c.reviewed": { \$ne: true } }] });
\`\`\`

**Important:** without an update operator, \`updateOne\` **replaces** the whole document.`,
      tags: ["core", "updates"],
    },
    {
      id: "indexes-basic",
      title: "Indexes: basics",
      difficulty: "easy",
      question: "How do indexes work in MongoDB?",
      answer: `An **index** is a B-tree-like structure that speeds up queries matching on specific fields.

\`\`\`js
db.users.createIndex({ email: 1 });                      // ascending
db.users.createIndex({ createdAt: -1 });
db.users.createIndex({ email: 1 }, { unique: true });    // unique constraint
db.users.createIndex({ "profile.name": "text" });        // text search
db.users.createIndex({ location: "2dsphere" });          // geospatial
\`\`\`

**Automatic:** \`_id\` is always indexed.

**When to add an index:**
- Fields used in query filters (\`WHERE\` equivalent).
- Fields used in sort orders.
- Fields used in \`\$match\` / \`\$group\` of aggregations.

**When to NOT add:**
- Fields you never filter/sort on — wasted storage + write overhead.
- Extremely low-cardinality fields (boolean with 50/50 split).

**Costs:**
- Extra storage (each index is a separate B-tree).
- Slower inserts/updates/deletes (every index must be maintained).
- Higher RAM working set (indexes should fit in RAM for optimal performance).

**Check what a query uses:**
\`\`\`js
db.users.find({ email: "x" }).explain("executionStats");
\`\`\`
Look for **\`stage: "IXSCAN"\`** (good) vs **\`"COLLSCAN"\`** (bad, full scan).`,
      tags: ["fundamentals", "indexing"],
    },

    // ───────── MEDIUM ─────────
    {
      id: "compound-indexes",
      title: "Compound indexes and the ESR rule",
      difficulty: "medium",
      question: "How do compound indexes work, and what's the ESR rule?",
      answer: `A **compound index** spans multiple fields: \`{ a: 1, b: 1, c: 1 }\`. Order matters — it's a B-tree sorted lexicographically by (a, b, c).

**Prefix rule:** a compound index supports queries using **a prefix of its fields in order**.
\`\`\`js
db.orders.createIndex({ userId: 1, createdAt: -1, status: 1 });

// ✅ uses the index
db.orders.find({ userId: "u1" }).sort({ createdAt: -1 });
db.orders.find({ userId: "u1", createdAt: { \$gte: d } });
db.orders.find({ userId: "u1", createdAt: { \$gte: d }, status: "paid" });

// ❌ can't use it (doesn't start with userId)
db.orders.find({ createdAt: { \$gte: d } });
\`\`\`

**The ESR rule — Equality, Sort, Range** — put fields in this order for optimal compound indexes:
1. **Equality** matches first (\`userId: "u1"\`)
2. **Sort** fields next (\`createdAt\`)
3. **Range** predicates last (\`createdAt: { \$gte: d }\`)

Reason: equality narrows a range of the B-tree to a tiny segment. Within it, sort fields keep index order (no in-memory sort). Range limits the scan further.

**Tips:**
- Sort direction in the index must match the sort direction in the query (or the exact inverse for reverse scans).
- One compound index often replaces multiple single-field indexes.
- \`explain\` shows \`IXSCAN\` with the index name — verify the planner picked what you expected.`,
      tags: ["indexing", "performance"],
    },
    {
      id: "aggregation-pipeline",
      title: "The aggregation pipeline",
      difficulty: "medium",
      question: "What is the aggregation pipeline?",
      answer: `A **pipeline** is an ordered sequence of stages that transforms documents step by step. Each stage's output is the next stage's input — similar to Unix pipes.

\`\`\`js
db.orders.aggregate([
  { \$match: { status: "paid", createdAt: { \$gte: lastMonth } } },
  { \$group: { _id: "\$userId", total: { \$sum: "\$amount" }, count: { \$sum: 1 } } },
  { \$sort: { total: -1 } },
  { \$limit: 10 },
  { \$lookup: { from: "users", localField: "_id", foreignField: "_id", as: "user" } },
  { \$unwind: "\$user" },
  { \$project: { _id: 0, userId: "\$_id", email: "\$user.email", total: 1, count: 1 } },
]);
\`\`\`

**Common stages:**
| Stage          | Purpose                                |
|----------------|----------------------------------------|
| \`\$match\`      | Filter (like \`find\`)                   |
| \`\$project\`    | Shape / compute fields                 |
| \`\$group\`      | Aggregate by key                       |
| \`\$sort\`       | Order                                  |
| \`\$limit\` / \`\$skip\` | Paginate                         |
| \`\$lookup\`     | Join another collection                |
| \`\$unwind\`     | Flatten array → one doc per element    |
| \`\$addFields\`  | Add computed fields without full project |
| \`\$facet\`      | Run multiple sub-pipelines in parallel |
| \`\$merge\` / \`\$out\` | Write results to a collection    |

**Performance tips:**
- Put \`\$match\` and \`\$sort\` **early** so indexes are used.
- \`\$project\` to drop large unused fields early.
- \`\$lookup\` is expensive — avoid it in hot paths; denormalize or use indexes on the joined field.`,
      tags: ["aggregation", "queries"],
    },
    {
      id: "lookup-joins",
      title: "$lookup and joins",
      difficulty: "medium",
      question: "How does $lookup work, and when should you avoid it?",
      answer: `**\`\$lookup\`** is MongoDB's left outer join — it pulls matching documents from another collection into an array field.

\`\`\`js
db.orders.aggregate([
  { \$lookup: {
      from: "users",
      localField: "userId",
      foreignField: "_id",
      as: "user"
  }},
  { \$unwind: "\$user" }            // flatten single-item array
]);
\`\`\`

**Advanced \`\$lookup\` with sub-pipeline** — join with conditions, projections, or multiple fields:
\`\`\`js
{ \$lookup: {
    from: "orders",
    let: { uid: "\$_id" },
    pipeline: [
      { \$match: { \$expr: { \$and: [{ \$eq: ["\$userId", "\$\$uid"] }, { \$eq: ["\$status", "paid"] }] } } },
      { \$project: { amount: 1 } }
    ],
    as: "paidOrders"
} }
\`\`\`

**Costs:**
- Each input document runs a lookup — effectively N subqueries.
- Indexes on the **foreign field** are crucial; without them, \`\$lookup\` does N full scans.
- Returning huge arrays blows up document size.

**When to avoid:**
- Hot read paths with large N → denormalize (embed frequently-joined data).
- Analytical queries over millions of rows → use a data warehouse.
- Sharded collections → \`\$lookup\` across shards has significant overhead.

**Rule of thumb:** design for the query so \`\$lookup\` is an occasional convenience, not the default pattern. Mongo rewards denormalization.`,
      tags: ["aggregation", "design"],
    },
    {
      id: "schema-design-patterns",
      title: "Schema design patterns",
      difficulty: "medium",
      question: "What are the common MongoDB schema design patterns?",
      answer: `- **Embedded documents** — nest related data when it's always read with the parent and bounded in size (user + addresses).
- **References** — separate collections linked by \`_id\` when children are large, unbounded, or independently queried.
- **Extended reference** — store both a reference *and* a copy of the fields you always show (author name/avatar in a post).
- **Bucket pattern** — group time-series data into buckets (e.g. one document per hour per device) to cut document count and reduce index size.
- **Computed pattern** — store pre-computed aggregates (sums, counts) updated on write for cheap reads.
- **Outlier pattern** — keep the common shape in the main document; move rare large fields (huge comment threads) to a separate collection linked by id.
- **Schema versioning** — include a \`schemaVersion\` field so you can migrate documents lazily on read.
- **Tree/hierarchy** patterns:
  - **Parent reference** (simple, good for shallow trees)
  - **Child references** (fast top-down reads)
  - **Materialized path** (store the path as a string: \`/root/childA/childB\` — fast ancestor queries)
  - **Nested sets / lineage arrays** — trade write complexity for read speed

**Design principle:** start from the **queries**. Ask "what do I fetch together, how often?" and let storage shape follow. Write amplification from denormalization is cheaper than the N round-trips a relational design would cause.`,
      tags: ["design", "modeling"],
    },
    {
      id: "replica-sets",
      title: "Replica sets",
      difficulty: "medium",
      question: "What is a replica set and how does it work?",
      answer: `A **replica set** is a group of 3+ \`mongod\` instances that maintain the same data: one **primary** and multiple **secondaries**.

**How it works:**
- All writes go to the **primary**, which appends them to the **oplog** (a capped collection).
- Secondaries tail the oplog and replay operations, staying in near-sync.
- If the primary fails or is partitioned, surviving nodes hold an **election** (Raft-like protocol) to promote a new primary. Typically completes in 10–30 seconds.
- Clients transparently reconnect to the new primary via the driver.

**Why run one:**
- **High availability** — automatic failover.
- **Durability** — writes are replicated to multiple disks.
- **Read scaling** (optional) — reads can go to secondaries with \`readPreference\`.
- **Disaster recovery** — a delayed member can act as a live backup of older state.

**Configurations:**
- **Arbiter** — participates in elections but stores no data. Use sparingly (no redundancy).
- **Hidden / delayed** secondaries — for backups or reporting without affecting application topology.

**Write concern** (\`w: majority\`) — acknowledge only after majority of members have applied. Safer, but higher latency. The default for production apps.`,
      tags: ["replication", "production"],
    },
    {
      id: "read-write-concern",
      title: "Write concern and read concern",
      difficulty: "medium",
      question: "What are write concern and read concern?",
      answer: `**Write concern** controls how many replica set members must acknowledge a write before it is considered successful.

\`\`\`js
db.users.insertOne(doc, { writeConcern: { w: "majority", j: true, wtimeout: 5000 } });
\`\`\`

- \`w: 1\` — acknowledged by primary only (**durability risk** on failover).
- \`w: "majority"\` — acknowledged by the majority. Survives primary crash → **the default for production**.
- \`w: 0\` — fire and forget. Not recommended.
- \`j: true\` — only after the journal is flushed to disk.
- \`wtimeout\` — bound how long to wait before returning an error.

**Read concern** controls the visibility of writes to readers:

| Level                | What you get                                                    |
|----------------------|-----------------------------------------------------------------|
| \`local\` (default)   | Latest on the queried node — may not be majority-acknowledged.  |
| \`available\`         | Same on replica set; relaxed on sharded clusters.               |
| \`majority\`          | Only data acknowledged by majority. Durable, may lag.           |
| \`linearizable\`      | Strong linearizable read (primary only, slower).                |
| \`snapshot\`          | Point-in-time consistent reads (used in transactions).          |

**Read preference** is a separate axis — which node to read from: \`primary\`, \`primaryPreferred\`, \`secondary\`, \`nearest\`. Combine with \`readConcern\` to pick your consistency/latency trade-off.

**Default recommendation:** \`w: "majority"\`, \`readConcern: "majority"\`, \`readPreference: "primary"\`.`,
      tags: ["consistency", "production"],
    },
    {
      id: "transactions",
      title: "Multi-document transactions",
      difficulty: "medium",
      question: "How do MongoDB transactions work?",
      answer: `MongoDB supports **multi-document ACID transactions** since 4.0 (replica sets) and 4.2 (sharded clusters). Usage pattern with the Node driver:

\`\`\`js
const session = client.startSession();
try {
  await session.withTransaction(async () => {
    await accounts.updateOne({ _id: fromId }, { \$inc: { balance: -amt } }, { session });
    await accounts.updateOne({ _id: toId   }, { \$inc: { balance:  amt } }, { session });
    await ledger.insertOne({ fromId, toId, amt, at: new Date() }, { session });
  });
} finally {
  await session.endSession();
}
\`\`\`

**\`withTransaction\`** handles **automatic retry** on transient errors (commit conflicts, primary failover).

**Defaults in a transaction:**
- \`readConcern: "snapshot"\` — all reads see the same snapshot.
- \`writeConcern: "majority"\`.
- Maximum runtime: 60 seconds by default.

**Limits:**
- 16 MB of uncommitted data per transaction.
- Creating collections / indexes inside a transaction is restricted.
- Performance overhead — every write takes the majority commit path.

**When NOT to use transactions:**
- Single-document updates — always atomic on a single document. Model the atomicity boundary **inside** one document first.
- Hot paths where latency matters — design around them (denormalize, event log, saga pattern).

**Rule of thumb:** single-document atomicity handles 90% of needs. Reach for transactions for the remaining genuinely multi-entity invariants (transfers, inventory + order).`,
      tags: ["transactions", "consistency"],
    },
    {
      id: "change-streams",
      title: "Change streams",
      difficulty: "medium",
      question: "What are change streams and what do you use them for?",
      answer: `**Change streams** expose the oplog as a real-time feed of changes on a collection, database, or cluster.

\`\`\`js
const stream = db.orders.watch([
  { \$match: { operationType: "insert", "fullDocument.amount": { \$gt: 1000 } } }
]);
for await (const change of stream) {
  notifySalesTeam(change.fullDocument);
}
\`\`\`

**Features:**
- **Resume token** — each event has \`_id\` you can persist. If your consumer crashes, resume from the last processed token; Mongo replays subsequent events if still in oplog retention.
- **Pipeline stages** — filter, project, even transform with \`\$lookup\` before events reach consumers.
- **Cluster-wide watching** — \`client.watch()\` monitors every change in every database.
- **Pre/post-images** — since 6.0, stream deletes with the prior document or updates with both before/after.

**Use cases:**
- **CDC-like integrations** — sync Elasticsearch, data warehouse, caches.
- **Event-driven architectures** — publish domain events without dual-writes.
- **Invalidations** — refresh computed views or caches when source data changes.
- **Audit trails** — log every change to a history collection.

**Caveats:**
- Oplog retention limits how far back you can resume. If the consumer lags, it must reinitialize.
- Not a full CDC platform (no large-scale fan-out, batching, ordering guarantees beyond per-key order). For big pipelines, use Kafka + Debezium Mongo source.`,
      tags: ["replication", "integration"],
    },
    {
      id: "text-search",
      title: "Text search and indexes",
      difficulty: "medium",
      question: "How does text search work in MongoDB?",
      answer: `**Text indexes** enable full-text search on string fields. Each collection can have one text index, covering multiple fields.

\`\`\`js
db.articles.createIndex({ title: "text", body: "text" }, { weights: { title: 10, body: 1 } });

// Query
db.articles.find(
  { \$text: { \$search: "mongodb aggregation -legacy", \$language: "english" } },
  { score: { \$meta: "textScore" } }
).sort({ score: { \$meta: "textScore" } });
\`\`\`

**Features:**
- **Stemming** per language (English, Spanish, etc.).
- **Stop word** removal.
- **Phrase queries** with quotes: \`"exact phrase"\`.
- **Negation** with a leading \`-\`.
- **Relevance score** via \`\$meta: "textScore"\`.

**Limits compared to a dedicated search engine (Atlas Search / Elasticsearch):**
- No fuzzy matching, typo tolerance, synonyms, analyzers beyond basic stemming.
- No faceted search, aggregations over hits.
- No boosting by function score.
- One text index per collection.

**Atlas Search** (on MongoDB Atlas) embeds Lucene, giving real full-text capabilities integrated with queries and aggregation. For anything beyond simple keyword search, Atlas Search or a separate Elasticsearch/Meilisearch is the right answer.

**Pro tip:** even with a great search index, pair it with structured filters (\`\$match\`) to keep result sets small before scoring.`,
      tags: ["search", "indexing"],
    },
    {
      id: "ttl-index",
      title: "TTL indexes",
      difficulty: "medium",
      question: "What is a TTL index?",
      answer: `A **TTL (Time-to-Live) index** automatically deletes documents after a configurable amount of time based on a date field.

\`\`\`js
db.sessions.createIndex({ expiresAt: 1 }, { expireAfterSeconds: 0 });
// when a doc's expiresAt passes, a background task removes it

// Or: expire N seconds after the field value
db.logs.createIndex({ createdAt: 1 }, { expireAfterSeconds: 60 * 60 * 24 * 30 }); // 30 days
\`\`\`

**How it works:**
- A background task (\`TTLMonitor\`) runs every ~60 seconds.
- It deletes expired documents in batches.
- Deletion is **not** instantaneous — you may see expired documents briefly.
- Deletions are logged in the oplog → replicated normally.

**Use cases:**
- Sessions, tokens, caches.
- Rate-limit counters.
- Log retention.
- GDPR-style auto-expiry.

**Limits:**
- Only works on **a single date field** (indexed value must be a Date or an array of Dates).
- Cannot be a compound index.
- Not suitable for capped collections (already size-limited).
- "At least this long, not exactly this long" — guaranteed minimum retention, not precise deletion.

**Alternative for soft-delete with grace period:** mark as expired with a flag and rely on TTL to eventually physically delete.`,
      tags: ["indexing", "operations"],
    },

    // ───────── HARD ─────────
    {
      id: "sharding",
      title: "Sharding",
      difficulty: "hard",
      question: "How does sharding work in MongoDB?",
      answer: `**Sharding** partitions a collection across multiple nodes (shards) to scale beyond a single machine's capacity.

**Components:**
- **mongos** — query router; the driver talks to it instead of shards directly.
- **Config servers** — metadata (chunk → shard map). A replica set of 3.
- **Shards** — each is itself a replica set.

**How it partitions:**
- You pick a **shard key** — one or more fields that determine which shard owns a document.
- Mongo divides the key space into **chunks** (~64 MB each).
- Chunks are distributed across shards and can be **split / migrated** by the balancer.

**Shard key strategies:**
- **Hashed** — \`{ userId: "hashed" }\`. Even distribution; no range scans.
- **Ranged** — \`{ region: 1, createdAt: 1 }\`. Preserves locality for ranges, risks hot chunks on monotonically increasing fields.
- **Compound** (recommended) — combine a high-cardinality field with a hashed part.
- **Zones** — pin chunks to specific shards based on key ranges (geo, compliance).

**Rules for a good shard key:**
- **High cardinality** (many distinct values).
- **Even write distribution** (no hotspots).
- **Supports the dominant queries** — so most reads hit a single shard.
- **Immutable** — changing a shard key value on a document is expensive (5.0+ allows it with overhead).

**Anti-patterns:**
- Sharding by \`{ createdAt: 1 }\` → all writes target the newest chunk.
- Sharding by an unused field → every query scatter-gathers.`,
      tags: ["scaling", "distributed"],
    },
    {
      id: "wiredtiger",
      title: "WiredTiger storage engine",
      difficulty: "hard",
      question: "What is WiredTiger and how does it affect performance?",
      answer: `**WiredTiger** has been MongoDB's default storage engine since 3.2. It powers document-level concurrency, compression, and snapshots.

**Key features:**
- **B-tree based** collections and indexes.
- **Document-level locking** — multiple writers to the same collection can proceed concurrently (vs the old MMAPv1's collection-level lock).
- **Compression** — Snappy by default for collections, prefix for indexes. Tunable: zstd (more CPU, better ratio), zlib.
- **Journal** — write-ahead log for durability. Flushed every 50 ms by default.
- **Checkpoints** — consistent on-disk snapshots every 60 seconds. Recovery replays journal from the last checkpoint.
- **MVCC snapshots** — readers see a consistent point-in-time view without blocking writers.

**Memory:**
- **WiredTiger cache** is the hot dataset resident in RAM. Default is 50% of (RAM - 1 GB). The OS page cache holds additional compressed blocks.
- **Working set** (frequently-accessed indexes + docs) should ideally fit in the cache for low-latency reads.

**Performance levers:**
- \`wiredTigerCacheSizeGB\` — cap or raise cache.
- Compression choice (\`zstd\` for cold data, Snappy default for hot).
- Adequate disk IOPS — WT is I/O sensitive, especially with a cold cache.
- Avoid massive documents — reads/writes amplify as whole docs are (de)compressed.

**Practical rule:** monitor \`wiredTiger.cache.bytes currently in the cache\` vs \`maximum bytes configured\`, and query \`serverStatus\` regularly. If your cache is hot full and reads touch disk constantly, scale up RAM or shard.`,
      tags: ["internals", "performance"],
    },
    {
      id: "explain-plans",
      title: "Explain plans and query tuning",
      difficulty: "hard",
      question: "How do you read an explain plan and tune a slow query?",
      answer: `\`\`\`js
db.orders.find({ userId: "u1", status: "paid" }).sort({ createdAt: -1 }).explain("executionStats");
\`\`\`

**Key sections:**
- **\`winningPlan\`** — the plan the optimizer picked.
- **\`rejectedPlans\`** — alternatives considered.
- **\`executionStats\`** — what actually happened on execution.

**Stage types to recognize:**
- **\`IXSCAN\`** — index scan. Good.
- **\`COLLSCAN\`** — full collection scan. Almost always bad at scale.
- **\`FETCH\`** — reads the document after an index scan.
- **\`SORT\` / \`SORT_KEY_GENERATOR\`** — in-memory sort. Check \`memUsage\`.
- **\`IDHACK\`** — \`_id\` direct lookup; fastest path.
- **\`PROJECTION_COVERED\`** — index satisfied the query entirely (no document read).

**Metrics to check:**
- \`totalDocsExamined\` vs \`nReturned\` — ratio should be near 1 for good selectivity.
- \`totalKeysExamined\` — index seeks.
- \`executionTimeMillis\` — total time.

**Common fixes:**
- **Create an index** following the **ESR rule** (equality → sort → range).
- **Covered queries** — all queried + returned fields are in the index; Mongo skips the document fetch.
- **Remove unselective fields from indexes** — indexes on booleans with 50/50 split rarely help.
- **Avoid \`\$regex\` without anchor** — \`^prefix\` is index-friendly, \`/substring/\` is not.
- **Aggregation \`\$match\` first**, push it before \`\$lookup\`/\`\$group\`.
- \`hint({ index })\` — force a specific index during tuning (remove before prod).`,
      tags: ["performance", "indexing"],
    },
    {
      id: "anti-patterns",
      title: "Common anti-patterns",
      difficulty: "hard",
      question: "What are the most common MongoDB anti-patterns?",
      answer: `- **Unbounded arrays** — push forever into a single document (\`"messages"\` on a room doc). Hits the 16 MB cap and kills write performance. Use the **bucket pattern** or a separate collection.
- **Massive documents** — big docs rewrite on every update; caches thrash. Keep documents focused on one aggregate.
- **Treating MongoDB like a relational DB** — everything normalized and joined with \`\$lookup\`. Denormalize for your access patterns.
- **\`allowDiskUse\` as a crutch** — aggregations spilling to disk mean your pipeline isn't using an index early enough.
- **Hot shard key** — monotonically increasing (ObjectId, date). Use hashed or composite.
- **Indexes on every field** — huge write amplification, RAM pressure. Index deliberately; drop unused ones (\`\$indexStats\`).
- **\`\$where\` and server-side JS** — slow, bypasses indexes, security risks.
- **Regex without anchor** — \`{ name: /.*foo.*/ }\` is a full scan.
- **No schema validation** — let the app write anything; years later you have 20 different shapes in one collection. Add \`\$jsonSchema\` validator.
- **Ignoring write concerns** — running \`w: 1\` in production is a durability bet.
- **Running \`findOne\` in a loop** — classic N+1. Batch with \`\$in\` or rethink the aggregate.
- **Using \`skip\` for deep pagination** — linear scan. Use keyset / range pagination.
- **Mixing reads across primary + secondary randomly** — inconsistent reads surprise users.

Know these and reviewers will trust your schema designs.`,
      tags: ["design", "performance"],
    },
    {
      id: "data-modeling-deep",
      title: "Embedding vs referencing in depth",
      difficulty: "hard",
      question: "How do you decide between embedding and referencing at scale?",
      answer: `**Embed when:**
- Child data is **always read with the parent** and **unbounded size is impossible**. (User addresses, profile, roles.)
- Child data is **owned** by the parent (life cycle tied together).
- Updates to the child don't happen from many places independently.

**Reference when:**
- Child is **large**, **unbounded**, or grows over time (user's posts, an event log).
- Child is **shared across many parents** (a product referenced from many orders).
- You need to query children independently (reporting over orders).
- Child has its own strong write semantics (frequent updates racing against reads).

**Hybrid — extended reference:**
- Embed a *snapshot* of a few fields you always show, reference for full details.
- Write amplification (keep the snapshot in sync) for read-path simplicity.

**Quantitative rules to check:**
- **16 MB doc limit** — if embedded arrays could blow past that, don't embed.
- **Working set** — if embedding makes hot docs too big to fit in RAM, reads slow. Split.
- **Contention** — if multiple writers update the same hot doc, document-level lock becomes a bottleneck.
- **Update pattern** — every \`\$push\` / \`\$set\` rewrites adjacent fields; on very hot fields, separate into its own document.

**Iterate:** most projects learn the right shape after seeing the access patterns in production. Build in \`schemaVersion\` and migration tooling from day one so you can evolve.`,
      tags: ["design", "advanced"],
    },
    {
      id: "index-strategies",
      title: "Advanced indexing strategies",
      difficulty: "hard",
      question: "What advanced indexing features should you know?",
      answer: `- **Partial indexes** — only index documents matching a predicate. Shrinks index size dramatically.
  \`\`\`js
  db.orders.createIndex({ userId: 1 }, { partialFilterExpression: { status: "paid" } });
  \`\`\`
- **Sparse indexes** — index only docs where the field exists. Useful for optional fields.
- **Wildcard indexes** — index any field under a path.
  \`\`\`js
  db.products.createIndex({ "attributes.\$**": 1 });
  \`\`\`
- **TTL indexes** — auto-expire documents.
- **Text indexes** — full-text search.
- **Geospatial** — \`2dsphere\` for earth-like coordinates, \`2d\` for flat.
- **Hashed indexes** — for equality only; used for hashed shard keys.
- **Unique + partial** — enforce uniqueness on a subset (e.g. unique email among active users).
- **Compound indexes** — covered separately; apply ESR rule.

**Covered queries:** when the query + projection only need fields present in an index, Mongo returns results **without fetching documents**. Huge win for read-heavy endpoints.

\`\`\`js
db.users.createIndex({ email: 1, name: 1 });
db.users.find({ email: "x" }, { _id: 0, name: 1 }); // covered
\`\`\`

**Index cost management:**
- Monitor with \`\$indexStats\` — drop unused indexes.
- Each index adds write overhead linearly.
- Keep the **working set** (hot indexes + hot documents) within the WiredTiger cache.

**Background builds (\`mongod\` 4.2+):** index builds default to online, no longer blocking writes, but can be resource-intensive.`,
      tags: ["indexing", "advanced"],
    },
    {
      id: "oplog",
      title: "The oplog",
      difficulty: "hard",
      question: "What is the oplog and why does its sizing matter?",
      answer: `The **oplog** is a capped collection on the primary (\`local.oplog.rs\`) that records **every write** in an idempotent form. Secondaries tail it to stay in sync; change streams consume it; point-in-time recovery relies on it.

**Characteristics:**
- **Capped collection** — fixed size (configurable, default a fraction of disk).
- **Idempotent** — replaying the same op twice is safe. Updates are rewritten into a deterministic form.
- **Per-document entries** — a \`deleteMany\` matching 1 M docs generates 1 M oplog entries.
- **Replicated**: exactly the same on all nodes.

**Why sizing matters:**
- The oplog determines the **maximum replication lag** a secondary can recover from. If a secondary falls behind further than the oplog's time window, it can no longer catch up from the oplog — a **full resync** is required (expensive, hours).
- Change stream consumers with persisted resume tokens can only go back as far as the oplog retains.

**Check size and window:**
\`\`\`js
rs.printReplicationInfo();
// configured oplog size: 1024 MB
// log length start to end: 48hrs (172800secs)
\`\`\`

**Rules of thumb:**
- A **24-hour minimum** window gives you time to notice and intervene before forced resyncs.
- For heavy writes or long-batch jobs, plan for **48–72 hours**.
- Modern Mongo supports \`replSetResizeOplog\` for online resizing.

**Monitoring:** track \`replication lag\` and the oplog time window as first-class metrics — lag spikes that approach the window are a production incident waiting to happen.`,
      tags: ["replication", "operations"],
    },
  ],
};
